updates:
  - directory: /
    package-ecosystem: github-actions
    schedule:
      interval: weekly
  - directory: /
    groups:
      eslint:
        patterns:
          - '@eslint/*'
          - '@stylistic/*'
          - eslint
          - eslint-*
          - typescript-eslint
      minor-and-patch:
        exclude-patterns:
          - '@eslint/*'
          - '@stylistic/*'
          - '@vitest/*'
          - eslint
          - eslint-*
          - typescript-eslint
          - vitest
        update-types:
          - minor
          - patch
      vitest:
        patterns:
          - '@vitest/*'
          - vitest
    package-ecosystem: npm
    schedule:
      interval: weekly
version: 2
