updates:
  - directory: /
    package-ecosystem: github-actions
    schedule:
      interval: daily
      time: '05:00'
  - directory: /
    package-ecosystem: npm
    schedule:
      interval: daily
      time: '05:00'
version: 2
