export type {
  ClassicEnergyDataAta,
  ClassicGetGroupData,
  ClassicGetGroupPostData,
  ClassicGroupState,
  ClassicListDeviceDataAta,
  ClassicSetDeviceDataAta,
  ClassicSetDeviceDataAtaInList,
  ClassicSetGroupPostData,
  ClassicUpdateDeviceDataAta,
  KeyOfClassicSetDeviceDataAtaNotInList,
} from './classic-ata.ts'
export type {
  ClassicEnergyDataAtw,
  ClassicHotWaterState,
  ClassicListDeviceDataAtw,
  ClassicOperationModeZoneDataAtw,
  ClassicSetDeviceDataAtw,
  ClassicTemperatureDataAtw,
  ClassicUpdateDeviceDataAtw,
  ClassicZoneAtw,
  ClassicZoneState,
} from './classic-atw.ts'
export type {
  ClassicBaseDevicePostData,
  ClassicBaseGetDeviceData,
} from './classic-bases.ts'
export type {
  ClassicListDeviceDataErv,
  ClassicSetDeviceDataErv,
  ClassicUpdateDeviceDataErv,
} from './classic-erv.ts'
export type {
  ClassicAreaData,
  ClassicAreaDataAny,
  ClassicAreaZone,
  ClassicBuildingData,
  ClassicBuildingWithStructure,
  ClassicBuildingZone,
  ClassicDateTimeComponents,
  ClassicDeviceZone,
  ClassicEnergyData,
  ClassicEnergyPostData,
  ClassicErrorLogData,
  ClassicErrorLogPostData,
  ClassicFailureData,
  ClassicFloorData,
  ClassicFloorZone,
  ClassicFrostProtectionData,
  ClassicFrostProtectionLocation,
  ClassicFrostProtectionPostData,
  ClassicGetDeviceData,
  ClassicGetDeviceDataParams,
  ClassicHolidayModeData,
  ClassicHolidayModeLocation,
  ClassicHolidayModePostData,
  ClassicHolidayModeTimeZone,
  ClassicListDevice,
  ClassicListDeviceAny,
  ClassicListDeviceData,
  ClassicListDeviceDataAny,
  ClassicLoginData,
  ClassicLoginPostData,
  ClassicOperationModeLogData,
  ClassicReportData,
  ClassicReportPostData,
  ClassicSetDeviceData,
  ClassicSetDevicePostData,
  ClassicSetPowerPostData,
  ClassicSettingsParams,
  ClassicSuccessData,
  ClassicTemperatureLogPostData,
  ClassicTilesData,
  ClassicTilesPostData,
  ClassicUpdateDeviceData,
  ClassicZone,
  ClassicZoneSettings,
} from './classic-generic.ts'
export type { LoginCredentials } from './credentials.ts'
export type {
  HomeAtaDeviceCapabilities,
  HomeAtaDeviceData,
  HomeAtaValues,
  HomeAtwDeviceCapabilities,
  HomeAtwDeviceData,
  HomeAtwOperationModeZone,
  HomeAtwValues,
  HomeBuilding,
  HomeClaim,
  HomeContext,
  HomeDeviceCapabilities,
  HomeDeviceCommonData,
  HomeDeviceConnectedInterfaceType,
  HomeDeviceData,
  HomeDeviceScheduleEntry,
  HomeDeviceSetting,
  HomeEnergyData,
  HomeEnergyMeasure,
  HomeEnergyPoint,
  HomeErrorLogEntry,
  HomeFrostProtection,
  HomeHolidayMode,
  HomeOverheatProtection,
  HomeReportData,
  HomeReportDataset,
  HomeReportPoint,
  HomeSystemInvite,
  HomeSystemInviteSystem,
  HomeSystemUnitType,
  HomeTokenResponse,
  HomeUser,
} from './home.ts'
export type { Hour } from './hour.ts'

export {
  type ClassicAreaID,
  type ClassicBuildingID,
  type ClassicDeviceID,
  type ClassicFloorID,
  toClassicAreaId,
  toClassicBuildingId,
  toClassicDeviceId,
  toClassicFloorId,
} from './ids.ts'
export {
  type ApiRequestError,
  type Failure,
  type Result,
  type Success,
  err,
  mapResult,
  ok,
} from './result.ts'
