/**
 * Namespaced barrel for the MELCloud Classic API surface. Re-exports every
 * `Classic*` symbol from the main index under shorter aliases, so consumers
 * can write `import * as classic from 'melcloud-api/classic'` and reach the
 * public API as `classic.API`, `classic.Device`, `classic.FanSpeed`, etc.
 */
export {
  type ClassicAPIAdapter as APIAdapter,
  type ClassicAPIConfig as APIConfig,
  type ClassicAPISettings as APISettings,
  type ClassicAreaData as AreaData,
  type ClassicAreaDataAny as AreaDataAny,
  type ClassicAreaID as AreaID,
  type ClassicAreaZone as AreaZone,
  type ClassicBaseDevicePostData as BaseDevicePostData,
  type ClassicBaseGetDeviceData as BaseGetDeviceData,
  type ClassicBuildingData as BuildingData,
  type ClassicBuildingFacade as BuildingFacade,
  type ClassicBuildingID as BuildingID,
  type ClassicBuildingWithStructure as BuildingWithStructure,
  type ClassicBuildingZone as BuildingZone,
  type ClassicDateTimeComponents as DateTimeComponents,
  type ClassicDeviceAny as DeviceAny,
  type ClassicDeviceAtwFacade as DeviceAtwFacade,
  type ClassicDeviceAtwHasZone2Facade as DeviceAtwHasZone2Facade,
  type ClassicDeviceFacade as DeviceFacade,
  type ClassicDeviceFacadeAny as DeviceFacadeAny,
  type ClassicDeviceID as DeviceID,
  type ClassicDeviceZone as DeviceZone,
  type ClassicEnergyData as EnergyData,
  type ClassicEnergyDataAta as EnergyDataAta,
  type ClassicEnergyDataAtw as EnergyDataAtw,
  type ClassicEnergyPostData as EnergyPostData,
  type ClassicErrorDetails as ErrorDetails,
  type ClassicErrorLog as ErrorLog,
  type ClassicErrorLogData as ErrorLogData,
  type ClassicErrorLogPostData as ErrorLogPostData,
  type ClassicErrorLogQuery as ErrorLogQuery,
  type ClassicFacade as Facade,
  type ClassicFailureData as FailureData,
  type ClassicFloorData as FloorData,
  type ClassicFloorID as FloorID,
  type ClassicFloorZone as FloorZone,
  type ClassicFrostProtectionData as FrostProtectionData,
  type ClassicFrostProtectionLocation as FrostProtectionLocation,
  type ClassicFrostProtectionPostData as FrostProtectionPostData,
  type ClassicFrostProtectionQuery as FrostProtectionQuery,
  type ClassicGetDeviceData as GetDeviceData,
  type ClassicGetDeviceDataParams as GetDeviceDataParams,
  type ClassicGetGroupData as GetGroupData,
  type ClassicGetGroupPostData as GetGroupPostData,
  type ClassicGroupState as GroupState,
  type ClassicHolidayModeData as HolidayModeData,
  type ClassicHolidayModeLocation as HolidayModeLocation,
  type ClassicHolidayModePostData as HolidayModePostData,
  type ClassicHolidayModeQuery as HolidayModeQuery,
  type ClassicHolidayModeTimeZone as HolidayModeTimeZone,
  type ClassicHotWaterState as HotWaterState,
  type ClassicListDevice as ListDevice,
  type ClassicListDeviceAny as ListDeviceAny,
  type ClassicListDeviceData as ListDeviceData,
  type ClassicListDeviceDataAny as ListDeviceDataAny,
  type ClassicListDeviceDataAta as ListDeviceDataAta,
  type ClassicListDeviceDataAtw as ListDeviceDataAtw,
  type ClassicListDeviceDataErv as ListDeviceDataErv,
  type ClassicLoginCredentials as LoginCredentials,
  type ClassicLoginData as LoginData,
  type ClassicLoginPostData as LoginPostData,
  type ClassicModel as Model,
  type ClassicNonSilentFanSpeed as NonSilentFanSpeed,
  type ClassicOperationModeLogData as OperationModeLogData,
  type ClassicOperationModeZoneDataAtw as OperationModeZoneDataAtw,
  type ClassicReportData as ReportData,
  type ClassicReportPostData as ReportPostData,
  type ClassicSetDeviceData as SetDeviceData,
  type ClassicSetDeviceDataAta as SetDeviceDataAta,
  type ClassicSetDeviceDataAtaInList as SetDeviceDataAtaInList,
  type ClassicSetDeviceDataAtw as SetDeviceDataAtw,
  type ClassicSetDeviceDataErv as SetDeviceDataErv,
  type ClassicSetDevicePostData as SetDevicePostData,
  type ClassicSetGroupPostData as SetGroupPostData,
  type ClassicSetPowerPostData as SetPowerPostData,
  type ClassicSettingsParams as SettingsParams,
  type ClassicSuccessData as SuccessData,
  type ClassicTemperatureDataAtw as TemperatureDataAtw,
  type ClassicTemperatureLogPostData as TemperatureLogPostData,
  type ClassicTilesData as TilesData,
  type ClassicTilesPostData as TilesPostData,
  type ClassicUpdateDeviceData as UpdateDeviceData,
  type ClassicUpdateDeviceDataAta as UpdateDeviceDataAta,
  type ClassicUpdateDeviceDataAtw as UpdateDeviceDataAtw,
  type ClassicUpdateDeviceDataErv as UpdateDeviceDataErv,
  type ClassicZone as Zone,
  type ClassicZoneAtw as ZoneAtw,
  type ClassicZoneFacade as ZoneFacade,
  type ClassicZoneSettings as ZoneSettings,
  type ClassicZoneState as ZoneState,
  ClassicAPI as API,
  ClassicArea as Area,
  ClassicBuilding as Building,
  classicCoolModes as coolModes,
  ClassicDevice as Device,
  ClassicDeviceType as DeviceType,
  ClassicFacadeManager as FacadeManager,
  ClassicFanSpeed as FanSpeed,
  CLASSIC_FLAG_UNCHANGED as FLAG_UNCHANGED,
  ClassicFloor as Floor,
  fetchDevices,
  ClassicHorizontal as Horizontal,
  hasClassicZone2 as hasZone2,
  classicHeatModes as heatModes,
  isClassicAtaFacade as isAtaFacade,
  isClassicAtwFacade as isAtwFacade,
  isClassicDeviceOfType as isDeviceOfType,
  isClassicErvFacade as isErvFacade,
  ClassicLabelType as LabelType,
  ClassicLanguage as Language,
  CLASSIC_OPERATION_MODE_MIXED as OPERATION_MODE_MIXED,
  ClassicOperationMode as OperationMode,
  ClassicOperationModeState as OperationModeState,
  ClassicOperationModeStateHotWater as OperationModeStateHotWater,
  ClassicOperationModeStateZone as OperationModeStateZone,
  ClassicOperationModeZone as OperationModeZone,
  ClassicRegistry as Registry,
  syncDevices,
  ClassicTemperature as Temperature,
  classicUpdateDevice as updateDevice,
  classicUpdateDevices as updateDevices,
  ClassicVentilationMode as VentilationMode,
  ClassicVertical as Vertical,
} from './index.ts'
