/**
 * Namespaced barrel for the MELCloud Home API surface. Re-exports every
 * `Home*` symbol from the main index under shorter aliases, so consumers can
 * write `import * as home from 'melcloud-api/home'` and reach the public API
 * as `home.API`, `home.Device`, `home.DeviceType`, etc.
 */
export {
  type HomeAPIAdapter as APIAdapter,
  type HomeAPIConfig as APIConfig,
  type HomeAPISettings as APISettings,
  type HomeAtaDeviceCapabilities as AtaDeviceCapabilities,
  type HomeAtaDeviceData as AtaDeviceData,
  type HomeAtaValues as AtaValues,
  type HomeAtwDeviceCapabilities as AtwDeviceCapabilities,
  type HomeAtwDeviceData as AtwDeviceData,
  type AtwHotWaterState,
  type HomeAtwOperationMode as AtwOperationMode,
  type HomeAtwOperationModeZone as AtwOperationModeZone,
  type HomeAtwValues as AtwValues,
  type AtwZoneState,
  type HomeBuilding as Building,
  type HomeBuildingDevices as BuildingDevices,
  type HomeBuildingRef as BuildingRef,
  type HomeBuildingZone as BuildingZone,
  type HomeClaim as Claim,
  type HomeContext as Context,
  type HomeDeviceCapabilities as DeviceCapabilities,
  type HomeDeviceCommonData as DeviceCommonData,
  type HomeDeviceConnectedInterfaceType as DeviceConnectedInterfaceType,
  type HomeDeviceData as DeviceData,
  type HomeDeviceFacadeAny as DeviceFacadeAny,
  type HomeDeviceScheduleEntry as DeviceScheduleEntry,
  type HomeDeviceSetting as DeviceSetting,
  type HomeDeviceValues as DeviceValues,
  type HomeDeviceZone as DeviceZone,
  type HomeEnergyData as EnergyData,
  type HomeEnergyMeasure as EnergyMeasure,
  type HomeEnergyPoint as EnergyPoint,
  type HomeEnergyQuery as EnergyQuery,
  type ErrorLogEntry,
  type HomeFanSpeed as FanSpeed,
  type HomeFlatZone as FlatZone,
  type HomeFrostProtection as FrostProtection,
  type HomeFrostProtectionPostData as FrostProtectionPostData,
  type HomeHolidayMode as HolidayMode,
  type HomeHolidayModePostData as HolidayModePostData,
  type HomeHorizontal as Horizontal,
  type HomeOperationMode as OperationMode,
  type HomeOverheatProtection as OverheatProtection,
  type HomeOverheatProtectionPostData as OverheatProtectionPostData,
  type HomeProtectionUnits as ProtectionUnits,
  type HomeReportAnnotation as ReportAnnotation,
  type HomeReportData as ReportData,
  type HomeReportDataset as ReportDataset,
  type HomeReportPoint as ReportPoint,
  type HomeReportTrigger as ReportTrigger,
  type HomeUser as User,
  type HomeUserContext as UserContext,
  type HomeVertical as Vertical,
  HomeAPI as API,
  HomeAtwOperationalState as AtwOperationalState,
  HomeAtwZoneMode as AtwZoneMode,
  HomeBaseDeviceFacade as BaseDeviceFacade,
  HomeBuildingFacade as BuildingFacade,
  HomeDevice as Device,
  HomeDeviceAtaFacade as DeviceAtaFacade,
  HomeDeviceAtwFacade as DeviceAtwFacade,
  HomeDeviceType as DeviceType,
  homeDeviceTypeFromClassic as deviceTypeFromClassic,
  homeDeviceTypeToClassic as deviceTypeToClassic,
  HomeFacadeManager as FacadeManager,
  fetchDevices,
  isHomeAtaFacade as isAtaFacade,
  isHomeAtwFacade as isAtwFacade,
  HomeRegistry as Registry,
  syncDevices,
} from './index.ts'
