export type { HolidayModeUpdate } from './holiday-mode.ts'
export type {
  ApiRequestError,
  ClassicAreaData,
  ClassicAreaDataAny,
  ClassicAreaID,
  ClassicAreaZone,
  ClassicBaseDevicePostData,
  ClassicBaseGetDeviceData,
  ClassicBaseListDevice,
  ClassicBuildingData,
  ClassicBuildingID,
  ClassicBuildingOwner,
  ClassicBuildingWithStructure,
  ClassicBuildingZone,
  ClassicDateTimeComponents,
  ClassicDeviceID,
  ClassicDevicePermissions,
  ClassicDeviceZone,
  ClassicEnergyData,
  ClassicEnergyDataAta,
  ClassicEnergyDataAtw,
  ClassicEnergyPostData,
  ClassicErrorLogData,
  ClassicErrorLogPostData,
  ClassicFailureData,
  ClassicFloorData,
  ClassicFloorID,
  ClassicFloorZone,
  ClassicFrostProtectionData,
  ClassicFrostProtectionLocation,
  ClassicFrostProtectionPostData,
  ClassicGetDeviceData,
  ClassicGetDeviceDataParams,
  ClassicGetGroupData,
  ClassicGetGroupPostData,
  ClassicGroupState,
  ClassicHolidayModeData,
  ClassicHolidayModeLocation,
  ClassicHolidayModePostData,
  ClassicHolidayModeTimeZone,
  ClassicHotWaterState,
  ClassicListDevice,
  ClassicListDeviceAny,
  ClassicListDeviceData,
  ClassicListDeviceDataAny,
  ClassicListDeviceDataAta,
  ClassicListDeviceDataAtw,
  ClassicListDeviceDataErv,
  ClassicLoginData,
  ClassicLoginPostData,
  ClassicOperationModeLogData,
  ClassicOperationModeZoneDataAtw,
  ClassicQuantizedCoordinates,
  ClassicReportData,
  ClassicReportPostData,
  ClassicSetDeviceData,
  ClassicSetDeviceDataAta,
  ClassicSetDeviceDataAtaInList,
  ClassicSetDeviceDataAtw,
  ClassicSetDeviceDataErv,
  ClassicSetDevicePostData,
  ClassicSetGroupPostData,
  ClassicSetPowerPostData,
  ClassicSettingsParams,
  ClassicSuccessData,
  ClassicTemperatureDataAtw,
  ClassicTemperatureLogPostData,
  ClassicTilesData,
  ClassicTilesPostData,
  ClassicUpdateDeviceData,
  ClassicUpdateDeviceDataAta,
  ClassicUpdateDeviceDataAtw,
  ClassicUpdateDeviceDataErv,
  ClassicZone,
  ClassicZoneAtw,
  ClassicZoneSettings,
  ClassicZoneState,
  Failure,
  HomeAtaDeviceCapabilities,
  HomeAtaDeviceData,
  HomeAtaValues,
  HomeAtwDeviceCapabilities,
  HomeAtwDeviceData,
  HomeAtwOperationMode,
  HomeAtwOperationModeZone,
  HomeAtwValues,
  HomeBuilding,
  HomeBuildingRef,
  HomeClaim,
  HomeContext,
  HomeDeviceCapabilities,
  HomeDeviceCommonData,
  HomeDeviceConnectedInterfaceType,
  HomeDeviceData,
  HomeDeviceScheduleEntry,
  HomeDeviceSetting,
  HomeEnergyData,
  HomeEnergyMeasure,
  HomeEnergyPoint,
  HomeErrorLogEntry,
  HomeFrostProtection,
  HomeFrostProtectionPostData,
  HomeHolidayMode,
  HomeHolidayModePostData,
  HomeOverheatProtection,
  HomeProtectionUnits,
  HomeReportAnnotation,
  HomeReportData,
  HomeReportDataset,
  HomeReportPoint,
  HomeReportTrigger,
  HomeUser,
  HomeUserContext,
  Hour,
  KeyOfClassicSetDeviceDataAtaNotInList,
  LoginCredentials,
  Resolved,
  Result,
  Success,
  UndefinedTolerant,
} from './types/index.ts'

export {
  type BaseAPIConfig,
  type ClassicAPIAdapter,
  type ClassicAPIConfig,
  type ClassicAPISettings,
  type ClassicErrorDetails,
  type ClassicErrorLog,
  type ClassicErrorLogQuery,
  type HomeAPIAdapter,
  type HomeAPIConfig,
  type HomeAPISettings,
  type LifecycleEvents,
  type Logger,
  type RequestCompleteEvent,
  type RequestErrorEvent,
  type RequestLifecycleContext,
  type RequestRetryEvent,
  type RequestStartEvent,
  type SettingManager,
  type SyncCallback,
  ClassicAPI,
  HomeAPI,
} from './api/index.ts'
export {
  type ClassicNonSilentFanSpeed,
  type DeviceType,
  CLASSIC_FLAG_UNCHANGED,
  CLASSIC_OPERATION_MODE_MIXED,
  ClassicDeviceType,
  ClassicFanSpeed,
  ClassicHorizontal,
  ClassicLabelType,
  ClassicLanguage,
  ClassicOperationMode,
  ClassicOperationModeState,
  ClassicOperationModeStateHotWater,
  ClassicOperationModeStateZone,
  ClassicOperationModeZone,
  ClassicTemperature,
  ClassicVentilationMode,
  ClassicVertical,
  classicCoolModes,
  classicHeatModes,
  HomeAtwOperationalState,
  HomeAtwZoneMode,
  HomeDeviceType,
} from './constants.ts'
export {
  classicUpdateDevice,
  classicUpdateDevices,
  fetchDevices,
  syncDevices,
} from './decorators/index.ts'
export {
  type ClassicDeviceAny,
  type ClassicModel,
  type HomeBuildingDevices,
  ClassicArea,
  ClassicBuilding,
  ClassicDevice,
  ClassicFloor,
  ClassicRegistry,
  HomeDevice,
  HomeRegistry,
  isClassicDeviceOfType,
} from './entities/index.ts'
export {
  type HomeFanSpeed,
  type HomeHorizontal,
  type HomeOperationMode,
  type HomeVertical,
  fanSpeedFromClassic,
  fanSpeedToClassic,
  homeDeviceTypeFromClassic,
  homeDeviceTypeToClassic,
  horizontalFromClassic,
  horizontalToClassic,
  operationModeFromClassic,
  operationModeToClassic,
  verticalFromClassic,
  verticalToClassic,
} from './enum-mappings.ts'
export {
  APIError,
  AuthenticationError,
  AuthenticationThrottledError,
  EntityNotFoundError,
  isAPIError,
  NetworkError,
  NoChangesError,
  RateLimitError,
  ValidationError,
} from './errors/index.ts'
export {
  type ClassicBuildingFacade,
  type ClassicDeviceAtaFacade,
  type ClassicDeviceAtwFacade,
  type ClassicDeviceAtwHasZone2Facade,
  type ClassicDeviceFacade,
  type ClassicDeviceFacadeAny,
  type ClassicFacade,
  type ClassicFrostProtectionQuery,
  type ClassicZoneFacade,
  type ReportChartBand,
  type ReportChartLineOptions,
  type ReportChartPieOptions,
  type ReportQuery,
  ClassicFacadeManager,
  HomeBaseDeviceFacade,
  HomeBuildingAtaFacade,
  HomeDeviceAtaFacade,
  HomeDeviceAtwFacade,
  HomeFacadeManager,
  hasClassicZone2,
  isClassicAtaFacade,
  isClassicAtwFacade,
  isClassicErvFacade,
} from './facades/index.ts'
export {
  type HttpClientConfig,
  type HttpRequestConfig,
  type HttpResponse,
  HttpClient,
  HttpError,
  isHttpError,
} from './http/index.ts'
export { Temporal } from './temporal.ts'
export { err, mapResult, ok } from './types/index.ts'
