# Calls the family workflow of the same name in OlivierZal/configs.
jobs:
  dependabot:
    permissions:
      contents: write
      pull-requests: write
    uses: OlivierZal/configs/.github/workflows/dependabot.yml@347191e7498bdc6fcd9907963f0fa6e7b2f55f4b # v1.10.1
name: dependabot
on:
  pull_request: {}
permissions: {}
