# Calls the family workflow of the same name in OlivierZal/configs.
jobs:
  pr_title:
    permissions:
      pull-requests: read
    uses: OlivierZal/configs/.github/workflows/pr-title.yml@e4c76f47b2966e2329aa85a94e9794dde64c1c40 # v1.10.0
name: pr-title
on:
  pull_request:
    types: [edited, opened, reopened, synchronize]
permissions: {}
